{% set version = "4.9.2" %}
{% set build = 2 %}

# ensure mpi is defined (needed for conda-smithy recipe-lint)
{% set mpi = mpi or 'nompi' %}

{% if mpi == 'mpich' %}
# prioritize mpich variant, which was previously the only option, via build number
{% set build = build + 100 %}
{% endif %}

package:
  name: nco
  version: {{ version }}

source:
  url: https://github.com/nco/nco/archive/{{ version }}.tar.gz
  sha256: 1a98c37c946c00232fa7319d00d1d80f77603adda7c9239d10d68a8a3545a4d5

build:
  number: {{ build }}
  skip: True  # [(win and vc<14) or (win and (mpi != 'nompi')) ]

  # add build string so packages can depend on
  # mpi or nompi variants explicitly:
  # `nco * mpi_mpich_*` for mpich
  # `nco * mpi_*` for any mpi
  # `nco * nompi_*` for no mpi

  {% if mpi != 'nompi' %}
  {% set mpi_prefix = "mpi_" + mpi %}
  {% else %}
  {% set mpi_prefix = "nompi" %}
  {% endif %}
  string: "{{ mpi_prefix }}_h{{ PKG_HASH }}_{{ build }}"

requirements:
  build:
    - cmake  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libblas
    - libcblas
    - antlr >=2.7.7,<3
    - bison  # [not win]
    - texinfo  # [not win]
    - flex  # [not win]
    - m4  # [not win]
    - curl
    - expat
    - gsl
    - krb5  # [not win]
    - udunits2
    - zlib
    - {{ mpi }}  # [mpi != 'nompi']
    # need to list these twice to get version pinning from conda_build_config
    # and build pinning from {{ mpi_prefix }}
    - hdf5
    - hdf5  * {{ mpi_prefix }}_*
    - libnetcdf
    - libnetcdf  * {{ mpi_prefix }}_*
  run:
    - curl
    - esmf * {{ mpi_prefix }}_*  # [not win]
    - expat
    - gsl
    - hdf5
    - krb5  # [not win]
    - libnetcdf
    - udunits2
    - tempest-remap * {{ mpi_prefix }}_*  # [not win]
    - {{ mpi }}  # [mpi != 'nompi']

test:
  source_files:
    - data/in.cdl
  commands:
    - ncks --help
    - ncap2 --help
    - ncks -M "http://tds.marine.rutgers.edu/thredds/dodsC/roms/espresso/2013_da/his/ESPRESSO_Real-Time_v2_History_Best"

about:
  home: http://nco.sourceforge.net/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Suite of programs for manipulating NetCDF/HDF4 files

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - xylar
