{% set version = "4.6.6" %}

package:
  name: nco
  version: {{ version }}

source:
  fn: nco-{{ version }}.tar.gz
  url: https://github.com/nco/nco/archive/{{ version }}.tar.gz
  sha256: 079d83f800b73d9b12b8de1634a88c2cbe40a639aaf7bc056cd2e836c6047697

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - gsl
    - antlr
    - curl
    - zlib 1.2.*
    - hdf5 1.8.17|1.8.17.*
    - libnetcdf 4.4.*
    - udunits2
    - expat
    - krb5
    - texinfo
    - bison
    - flex 2.6.0
    - m4
  run:
    - gsl
    - hdf5 1.8.17|1.8.17.*
    - libnetcdf 4.4.*
    - udunits2
    - expat
    - libgcc
    - esmf
    - openblas

test:
  source_files:
    - data/in.nc
  commands:
    - ncks --help
    - ncap2 --help
    - conda inspect linkages -p $PREFIX nco  # [not win]
    - conda inspect objects -p $PREFIX nco  # [osx]

about:
  home: http://nco.sourceforge.net/
  license: GPL-3.0
  summary: 'Suite of programs for manipulating NetCDF/HDF4 files.'

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
