package:
    name: nco
    version: 4.5.5

source:
    git_url: https://github.com/nco/nco.git
    git_tag: 4.5.5

build:
    number: 4
    skip: True  # [win]

requirements:
    build:
        - gsl
        - antlr
        - curl
        - zlib 1.2*
        - hdf5 1.8.15*
        - libnetcdf 4.3*
        - udunits2
        - expat
        - krb5
        - texinfo
    run:
        - gsl
        - hdf5 1.8.15*
        - libnetcdf 4.3*
        - udunits2
        - expat
        - libgcc
        - krb5

test:
    commands:
        - ncks --help
        - ncks -M http://test.opendap.org:80/opendap/data/ncml/sample_virtual_dataset.ncml
        - ncks -F --dimension samples,1 http://test.opendap.org:80/opendap/data/ncml/sample_virtual_dataset.ncml
        - ncap2 --help
        - conda inspect linkages -n _test nco  # [linux]

about:
    home: http://nco.sourceforge.net/
    license: GPL-3.0
    summary: Suite of programs for manipulating NetCDF/HDF4 files

extra:
    recipe-maintainers:
        - ocefpaf
        - kwilcox
