travis:
  secure:
    BINSTAR_TOKEN: bhkKJgAFbtMWtb+h2dEVPUkWGw33q/cpHOl39glT+6bZEtgiKTvGRVHzaiDua4XTBf3/8A1JwP8WKHxAJiytuXtJMzxR4UM2TjBN8VSUvjNC/sgjw/UzHZQ4INlcnuFYC4mDGa0z3jZHuuoesfmOYXFm8JLDYEHh7qrCCc4J27sodJEtiBnz/q3ESeIcmpVpDINAVKJW4zLLyY6qq4FkUJD2sy2O4x6TeVJeg4xuWB/OVyCRcjZ98vGtxw4yhzciUSAjbMA1WEGklPlPzxvNXf/w6zJn4RED+nzHY7NcTK+hLEvEGZ0WLJ4taBVLO/lgauerq4kpom2Psh/eo1Iy0AYxVbffLcv+qeJYWaGBqe4mKSp6ja8gVyaYPjvMn5AUNNfsdM2hu+Y/cEsMVfZkjqDFsHjDUo/G016WWhyeTR+rWahjYqVLWHeWFkRFX0vdska0/ewAcKHcMnYe3AoBR0NKut9aD4CRJG1I8oypEnJ7sU4TiP0GOFOiXh8y0uo9N9HBqdhz+1VysrKTOzIzw3kRpSMGmDZsWSjvaMYngqhtPJnQsNRi+TqFGbMKoBTK6ONX9FWxuhURX7Ma4EpJYZTID0jlqt8mfPSrhl61lPl1kJec/d5HeEn93I4VV6DZ1Yz1FRonDvWgUmeZSbt+fDG40G5a2mmvKJAVyORxSSY=
appveyor:
  secure:
    BINSTAR_TOKEN: KDvUkPrcdKmV2MxakkyQlrLA0rE/6WSuXxD42UezzZjCB0TRqnnOeebSW03/SnFP
